/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CustomGUI;

public class App {

    public static void main(String[] args) {
        new CustomGUI(50, 16, 9);
    }
}
